### ISSUE TITLE
训练过程中利用item取出loss值会出现非法地址访问的error

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#205]
## 环境
1.系统环境：Ubuntu 18.04
2.MegEngine版本：1.5.0
3.python版本：3.7.0

## 复现步骤
1.计算损失
2.损失回传
3.用item取出损失

## 请提供完整的日志及报错信息
```shell
Traceback (most recent call last):
  File "cityscapes_train.py", line 294, in <module>
    main()
  File "cityscapes_train.py", line 250, in main
    train(model, train_loader, val_loader, optimizer, loss_fn, gm, epochs, args, lr_scheduler=lr_sche)
  File "cityscapes_train.py", line 158, in train
    results = train_val_step(model, train_dataloader, val_dataloader, optimizer, loss_fn, gm, epoch, args, log_file, kwargs)
  File "cityscapes_train.py", line 61, in train_val_step
    losses += loss.detach().item()
  File "/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/tensor/array_method.py", line 426, in item
    return self.numpy().item()
  File "/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/tensor.py", line 143, in numpy
    return super().numpy()
RuntimeError: cuda error 700: an illegal memory access was encountered (cudaEventSynchronize(m_cuda_event) at ../../../../../../src/core/impl/comp_node/cuda/comp_node.cpp:host_wait_cv:650)

backtrace:
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN3mgb9CudaErrorC1ERKSs+0x54) [0x7f1ebec2f5e4]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN3mgb14_on_cuda_errorEPKc9cudaErrorS1_S1_i+0x6a) [0x7f1ebec0e7ca]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(+0x2b6d162) [0x7f1ebebf7162]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/_imperative_rt.cpython-37m-x86_64-linux-gnu.so(+0x22cf6b) [0x7f1f17bddf6b]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/_imperative_rt.cpython-37m-x86_64-linux-gnu.so(+0x1c6369) [0x7f1f17b77369]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/_imperative_rt.cpython-37m-x86_64-linux-gnu.so(+0x19c1f1) [0x7f1f17b4d1f1]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/_imperative_rt.cpython-37m-x86_64-linux-gnu.so(+0x19c54a) [0x7f1f17b4d54a]
python(_PyMethodDef_RawFastCallKeywords+0x141) [0x562242e01791]
python(_PyCFunction_FastCallKeywords+0x21) [0x562242e019d1]
python(_PyEval_EvalFrameDefault+0x4e0a) [0x562242e6de5a]
(last_err=700(an illegal memory access was encountered) device=0 mem_free=0.000MiB mem_tot=0.000MiB)
````

**Comment by Qsingle** [comment]
设置`MEGENGINE_INTERP_ASYNC_LEVEL=0`和`CUDA_LAUNCH_BLOCKING=1`，追查到如下报错日志:
```shell
Traceback (most recent call last):
  File "cityscapes_train.py", line 300, in <module>
    main()
  File "cityscapes_train.py", line 256, in main
    train(model, train_loader, val_loader, optimizer, loss_fn, gm, epochs, args, lr_scheduler=lr_sche)
  File "cityscapes_train.py", line 163, in train
    results = train_val_step(model, train_dataloader, val_dataloader, optimizer, loss_fn, gm, epoch, args, log_file, kwargs)
  File "cityscapes_train.py", line 65, in train_val_step
    gm.backward(loss)
  File "/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/autodiff/grad_manager.py", line 291, in backward
    self._grad(ys, dys)
  File "/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/autodiff/grad.py", line 78, in __call__
    self._impl.backward(ys, dys)
  File "/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/autodiff/grad.py", line 37, in backward
    return core2.backward(self, ys, dys)
RuntimeError: cuda error an illegal memory access was encountered(700) occurred; expr: cudaGetLastError()

backtrace:
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN3mgb13MegBrainErrorC1ERKSs+0x4a) [0x7f2a20a243ca]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(+0x2ba4f77) [0x7f2a20a70f77]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN6megdnn12ErrorHandler15on_megdnn_errorERKSs+0x14) [0x7f2a20e78e54]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN6megdnn12ErrorHandler15on_megdnn_errorEPKc+0x22) [0x7f2a20e7a842]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN6megdnn4cuda20__throw_cuda_error__E9cudaErrorPKc+0x35) [0x7f2a21ea2215]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(+0x5ab12ea) [0x7f2a2397d2ea]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN6megdnn4cuda18ResizeBackwardImpl4execERKNS_8TensorNDES4_RKNS_9WorkspaceE+0x127) [0x7f2a21e8d1b7]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(+0x2d1e22f) [0x7f2a20bea22f]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(+0x2bd8340) [0x7f2a20aa4340]
/data/public/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/core/lib/libmegengine_export.so(_ZN3mgb2cg5mixin20SingleCNOperatorNode16mixin_do_executeERNS0_16OperatorNodeBaseERNS0_15GraphExecutable7ExecEnvE+0xc3) [0x7f2a20aa36f3]
```
附件为出错的`interpolate`的输入
[dump.zip](https://github.com/MegEngine/MegEngine/files/7084013/dump.zip)

**Comment by Qsingle** [comment]
更新:
如果设定`align_corners=True`的话则不会出现这个问题

**Comment by youzhedian** [comment]
你好，可以补充一下关键的代码片段吗？便于复现问题

**Comment by Qsingle** [comment]
> 你好，可以补充一下关键的代码片段吗？便于复现问题

没有整理出一个比较好的最小复现，用我现在那个就太大了，也不太好定位问题,我也不确定以下代码是否就会出现这个问题。
```python
import megengine as mge
import megengine.module as M
import megengine.audodiff as ad
import megengine.optimizer as optim
import megengine.functional as F

class Model(M.Module):
    def __init__(self):
        self.conv1 = M.Conv2d(3, 64, 3, 1, 1)
        self.conv2 = M.Conv2d(64, 64, 3, 2, 1)
        self.conv3 = M.Conv2d(64, 32, 3, 2, 1)
    def forward(self,x):
        net = self.conv1(x)
        net = self.conv2(net)
        net = self.conv3(net)
        out = F.interpolate(net,size=x.shape[2:])
        return out

model = Model()
opt = optim.SGD(model.parameters(), 0.01, 0.9, 5e-4)
gm = ad.GradManager()
gm.attach(model.parameters())
for epoch in range(32):
    for data,label in dataloader:
        with gm:
            out = model(data)
            loss = F.loss.cross_entropy(data, label)
            gm.backward(loss)
```

数据的pipeline辛苦你们自己补充一下下啦，不过这个不一定能够造成那个问题

**Comment by gaohuazuo** [comment]
从报错看是 resize backward 算子的问题，但我们目前未能复现此问题。不过可以确认  input 或 output 的 height / width 中含有 0 时会产生类似的报错。

**Comment by Thzny** [comment]
> 更新: 如果设定`align_corners=True`的话则不会出现这个问题

请问您这一句是在哪设定的，我也出现同样的问题了

**Comment by youzhedian** [comment]
https://www.megengine.org.cn/doc/master/zh/reference/api/megengine.functional.nn.interpolate.html?highlight=align_corners%20true#megengine.functional.nn.interpolate  
`align_corners=True`是用于设定resize的时候是否中心点对齐

**Comment by Thzny** [comment]
谢谢 添加后问题解决了
